### ISSUE TITLE
bughuntoor - `mgCvg` balances are wrongfully calculated

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2023-11-convergence-judging#14]
bughuntoor

medium

# `mgCvg` balances are wrongfully calculated

## Summary
Users with significant difference in their locks may have the same `mgCVG` voting power 

## Vulnerability Detail
The `mgCvgCreated` is based on the amount a user has used for voting and their `lockDuration`. However, due to rounding down within the VotingEscrow contract, same users may get unfairly rewarded in comparison to others. 
Let's look at the code responsible for the `mgCvgCreated` amount within `mintPosition`
```solidity
        if (ysPercentage != MAX_PERCENTAGE) {
            uint256 amountVote = amount * (MAX_PERCENTAGE - ysPercentage);

            /** @dev Timestamp of the end of locking. */
            _cvgControlTower.votingPowerEscrow().create_lock(
                tokenId,
                amountVote / MAX_PERCENTAGE,
                block.timestamp + (lockDuration + 1) * 7 days
            );
            /// @dev compute the amount of mgCvg
            _mgCvgCreated = (amountVote * lockDuration) / (MAX_LOCK * MAX_PERCENTAGE);

            /// @dev Automatically add the veCVG and mgCVG in the balance taken from Snapshot.
            if (isAddToManagedTokens) {
                _cvgControlTower.lockingPositionDelegate().addTokenAtMint(tokenId, receiver);
            }
        }
```
As we know, the voting escrow contract round downs the lock time to the nearest week. However, this is not accounted for when calculating the `mgCvgCreated`. The amount is entirely based on the `lockDuration`. 
Consider the following scenario: 
If two users with equal stake both call `mintPosition` with the same `lockDuration` of (let's say) 2 weeks), but one calls it at the beginning of the week and the other one calls it at the end of the week. Because of the rounding down to the nearest week, one of the users will have locked their tokens for ~2 weeks, while the other one will have locked them for ~1 week. However, both users will receive the same amount of `mgCvg`. This is unfair for both users.

## Impact
Unfair calculation of `mgCvg`

## Code Snippet
https://github.com/sherlock-audit/2023-11-convergence/blob/main/sherlock-cvg/contracts/Locking/LockingPositionService.sol#L266C1-L282C10

## Tool used

Manual Review

## Recommendation
Base the `mgCvg` calculated on the block.timestamp

Duplicate of #136

**Comment by CergyK** [comment]
Escalate

This is a duplicate of #136 and/or #10, even though the root cause is the same the impact is worded slightly differently

**Comment by sherlock-admin2** [comment]
> Escalate
> 
> This is a duplicate of #136 and/or #10, even though the root cause is the same the impact is worded slightly differently

You've created a valid escalation!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by deadrosesxyz** [comment]
the issues mentioned above have close to nothing in common
#14 is about wrong calculation of mgCvg
#136 is about unintenionally locking the tokens for a week extra
#10 is about crossing a week’s end/ starting new week and resulting in wrong rewards distribution.

**Comment by 10xhash** [comment]
#136 #178 Both these issues reports the difference b/w the unlock time in cvgCycle and the unlock time in veCvg which could at max differ by 1. Hence these should be marked duplicates. #136  is infact not accurate since it is not the specialty of increaseLockTime but can happen with mintPosition also (see #59  which is duplicated with issue).

This issue says that the amount of mgCvg minted is same even if the actual lock times is different. This decision is design dependent and could be the expected behaviour of the system since cvgCycles are designed discretely. This can be seen in sdtStaking where no matter at which point in cvgCycle 1 a user stakes, the amount will only be counted from cvgCycle 2. Here too although both user's have different actual lock times, the end result is the same.
There is advantage gained by the user who have actually locked more time in the form of higher veCvg minted.

The issue #10  is about the possibility of change in overall gauge weightings and hence the reward distribution b/w two calls to writeStakingRewards. Multiple reasons can cause this (see #193 ) of which one is associated with the week timing and is not the root cause.

**Comment by nevillehuang** [comment]
My initial thoughts were exactly the same as @10xhash, so I am inclined to agree with him. 

I think #136 and its duplicates are all invalid because the impact described doesn't warrant medium severity, because locking for an additional 1 week is not permanent DoS and only has the impact of opportunity loss of access to funds which is historically not accepted as a finding on sherlock.

**Comment by CergyK** [comment]
> My initial thoughts were exactly the same as @10xhash, so I am inclined to agree with him.
> 
> I think #136 and its duplicates are all invalid because the impact described doesn't warrant medium severity, because locking for an additional 1 week is not permanent DoS and only has the impact of opportunity loss of access to funds which is historically not accepted as a finding on sherlock.

Both are saying the same thing, #136 is saying that for same mgCvg created users lock Cvg one week extra, #14 says users locking for one extra week receive same mgCvg as users locking at the end of the week.

Also I think @10xhash point is that this issue should be invalid as it is simply a design choice to discretize on cycles.

**Comment by 10xhash** [comment]
> > My initial thoughts were exactly the same as @10xhash, so I am inclined to agree with him.
> > I think #136 and its duplicates are all invalid because the impact described doesn't warrant medium severity, because locking for an additional 1 week is not permanent DoS and only has the impact of opportunity loss of access to funds which is historically not accepted as a finding on sherlock.
> 
> Both are saying the same thing, #136 is saying that for same mgCvg created users lock Cvg one week extra, #14 says users locking for one extra week receive same mgCvg as users locking at the end of the week.
> 
> Also I think @10xhash point is that this issue should be invalid as it is simply a design choice to discretize on cycles.

yes, i think this issue should be invalid since it is a design choice

**Comment by nevillehuang** [comment]
@10xhash @CergyK 

Based on sponsors acknowledgment of timing discrepancies between cycles, I think it is definitely not design choice imo. I am merely basing it off of the impact (issue/vector/path) described for validity.

@10xhash can you point to me the logic in stdstaking you are referring to? I'm not sure if its appropriate to associate a different contracts behavior with the current one.

**Comment by CergyK** [comment]
> @10xhash @CergyK
> 
> Based on sponsors acknowledgment of timing discrepancies between cycles, I think it is definitely not design choice imo. I am merely basing it off of the impact (issue/vector/path) described for validity.
> 
> @10xhash can you point to me the logic in stdstaking you are referring to? I'm not sure if its appropriate to associate a different contracts behavior with the current one.

The sponsor acknowledges that the timing discrepancy between the cycles in Convergence, and underlying locking voting escrows (forked from curve-dao) can cause problems. This happens because underlying voting-escrows cycles are `hardly` pinned to weeks see:
https://github.com/sherlock-audit/2023-11-convergence/blob/main/sherlock-cvg/contracts/Locking/veCVG.vy#L365

whereas Convergence start cycles when the corresponding function `_triggerCvgCycle` is called:
https://github.com/sherlock-audit/2023-11-convergence/blob/main/sherlock-cvg/contracts/Rewards/CvgRewards.sol#L345
 
This is not mentioned at all in this issue

**Comment by 10xhash** [comment]
https://github.com/sherlock-audit/2023-11-convergence/blob/e894be3e36614a385cf409dc7e278d5b8f16d6f2/sherlock-cvg/contracts/Staking/StakeDAO/SdtStakingPositionService.sol#L300
if u deposit sdtasset at anytime in this cvgCycle, it is counted as deposited in the next cvgCycle. Hence it chosen to associate with cvgCycle instead of time which can be the case with mgCvg too. Other time dependent benefits like veCvg minted will favor the user who has actually locked for more time.

**Comment by nevillehuang** [comment]
I think all issues mentioned [here in this comment](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/10#issuecomment-1859865845) has the possibility of being duplicates since all of them is dependent on cycles being too long/too short given cvgCycles are not synchronized exactly with WEEKS.

However, I will have to double-check all the mentioned root causes as well as attack paths/issues/impact described to make a decision on validity. My initial BUT NOT FINAL thoughts are the following:

#14, #59, #136, #215 - I agree that #14 is a duplicate of this issues too, but the impact described is what warrants it medium severity, the other issues are simply mentioning users would lock for an extra week but never mentioned anything about mgCVG balance (please correct me if I'm missing something). I don't think any information publicly is clear enough to mention this is intended design decision, especially not so when sponsor explicitly acknowledged the issue that it is giving users free mgCVG. 

#10 and #178 and its duplicates - Agree with @IAm0x52 [comments here](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/10#issuecomment-1870000723)

**Comment by Czar102** [comment]
As the Lead Judge suggested, planning to make #14 a duplicate of #136.

**Comment by deadrosesxyz** [comment]
hey @Czar102 could you please elaborate on that. 

#10 Summary
> due to rounding down within the VotingEscrow contract, same users may get unfairly rewarded in comparison to others.

#136 Summary
> the lock duration might extend an additional week more than intended

#10 Impact - unfair `mgCvg` balances between users
#136 Impact - unintended lock for extra time 

#10 Fix - base the `mgCvg` balances on the `block.timestamp` (same way as it happens in the VotingEscrow)
#136 Fix - Align the locking mechanism to multiples of a week and use `(block.timestamp % WEEK) + lockDuration`

Both issues have different summary, different impact and different fix. Fixing #10 would not fix #136 and vice versa - fixing #136 would not fix #10.

**Comment by walk-on-me** [comment]
MgCvg is not computed wrongly. The wrong thing is that there can be some discrepancies between the lock duration on ve and mg because we take the cycleId & not the block timestamp to compute the lockingDuration.

#10 is something real but very unlikely to happen as the distribution can be done by anyone AND we'll trigger it each week. Nothing can definitely correct this ( even puting a require asserting that we are not close to the end of cycle is not a perfect solution because if it happens, it means we missed the trigger of CVG rewards for one full cycle. )

#136 Is indeed different and is corrected by taking the cycle on locking in time and not anymore with the cycle

**Comment by Czar102** [comment]
I think @deadrosesxyz meant to compare #14 and #136.

**Comment by walk-on-me** [comment]
Sorry my bad, 
I do agree that issues (#14 and #136 ) are both different and have different impacts but comes from the same source.

Both will be corrected by the same fix which is to take the block.timestamp as reference of the lock and not anymore the cycleId

**Comment by Czar102** [comment]
In that case, according to Sherlock rules, they will be considered duplicates.

**Comment by Czar102** [comment]
Result:
Medium
Duplicate of #136

**Comment by sherlock-admin2** [comment]
Escalations have been resolved successfully!

Escalation status:
- [CergyK](https://github.com/sherlock-audit/2023-11-convergence-judging/issues/14/#issuecomment-1869567648): accepted
